const Employeeremove = {"body":{"type":"object","required":["email"],"properties":{"email":{"type":"string","description":"The employee email.","examples":["john@example.com"]}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"response":{"200":{"type":"object","properties":{"isSuccess":{"type":"boolean","default":true,"examples":[true]}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Employeesave = {"body":{"type":"object","properties":{"firstName":{"type":"string","description":"The employee first name.","examples":["John"]},"lastName":{"type":"string","description":"The employee last name."},"jobTitle":{"type":"string","description":"The employee job title."},"imageDataBase64":{"type":"string","description":"The employee image data encoded in base64. Maximum size of 3Mb."}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"email":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#","description":"The email of the Employee to update."}},"required":["email"]}]},"response":{"200":{"type":"object","properties":{"isSuccess":{"type":"boolean","default":true,"examples":[true]}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Engagement = {"body":{"type":"object","required":["dates"],"properties":{"groupNames":{"type":"array","description":"If null, returns the engagement reports for all company users","default":["Awesome team"],"items":{"type":"string"}},"dates":{"type":"array","description":"There is a limit of 20 dates.","items":{"type":"string","format":"date"}}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"response":{"200":{"type":"object","properties":{"weeklyReports":{"type":"array","items":{"type":"object","properties":{"date":{"type":"string","examples":["2016-06-02"]},"groupName":{"type":"string","examples":["Officevibe"]},"metricsValues":{"type":"array","items":{"type":"object","properties":{"id":{"type":"string","examples":["MG-10"]},"displayName":{"type":"string","examples":["Ambassadorship"]},"value":{"type":"number","default":0,"examples":[8.5]}}}}}}}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Feedback = {"body":{"type":"object","required":["email","isAnonymous","content"],"properties":{"email":{"type":"string","description":"The email of the user who created the feedback. WARNING : do not let the user specify his email, enter the email in your back-end.","examples":["bob@test.com"]},"isAnonymous":{"type":"boolean","description":"Specifies if the feedback is anonymous.","default":true},"content":{"type":"string","description":"The content of feedback."}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"response":{"200":{"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Feedbackid = {"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#","description":"The id of the feedback to retrieve."}},"required":["id"]}]},"response":{"200":{"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Feedbacklabels = {"response":{"200":{"type":"object","properties":{"isSuccess":{"type":"boolean","default":true,"examples":[true]},"errorMessage":{},"data":{"type":"array","items":{"type":"object","properties":{"id":{"type":"string","examples":["CT-1"]},"title":{"type":"string","examples":["Important"]},"color":{"type":"string","examples":["custom-tag1"]}}}}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Feedbacklist = {"metadata":{"allOf":[{"type":"object","properties":{"groupName":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#","description":"The name of the group to retrieve feedback. If null, it retrieves feedback for All Company."},"metric":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#","description":"Filter the feedback with a specific metric, ex : \"MG-1\". See documentation below."},"tone":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#","description":"Filter the feedback with a specific tone, ex : \"FP\". See documentation below."},"type":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#","description":"Filter the feedback with a specific type, ex : \"POLL\". See documentation below."},"label":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#","description":"Filter the feedback with a specific label, ex : \"CT-1\". See documentation below."},"fromDate":{"type":"string","format":"date","$schema":"https://json-schema.org/draft/2020-12/schema#","description":"Filter the feedback from a specified creation date. (original feedback)"},"toDate":{"type":"string","format":"date","$schema":"https://json-schema.org/draft/2020-12/schema#","description":"Filter the feedback to a specified creation date (original feedback)."}},"required":[]}]},"response":{"200":{"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Group = {"response":{"200":{"type":"object","properties":{"isSuccess":{"type":"boolean","default":true,"examples":[true]},"data":{"type":"object","properties":{"groupCount":{"type":"integer","default":0,"examples":[1]},"groups":{"type":"array","items":{"type":"object","properties":{"id":{"type":"string","examples":["9345c237-c166-48ec-af1c-705b9a057be4"]},"name":{"type":"string","examples":["Officevibe"]},"groupType":{"type":"string","examples":["Department"]},"userCount":{"type":"integer","default":0,"examples":[10]},"managerCount":{"type":"integer","default":0,"examples":[2]}}}}}}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Groupaddemployee = {"body":{"type":"object","required":["groupId","emails"],"properties":{"groupId":{"type":"string","description":"The group name or id.","examples":["9345c237-c166-48ec-af1c-705b9a057be4"]},"emails":{"type":"array","description":"The user emails. The users will be created if not matched to any existing.","items":{"type":"string"}},"toManagers":{"type":"boolean","description":"Add the users to the managers list.","default":false},"toMembers":{"type":"boolean","description":"Add the users to members list.","default":true}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"response":{"200":{"type":"object","properties":{"isSuccess":{"type":"boolean","default":true,"examples":[true]}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Groupremove = {"body":{"type":"object","required":["groupId"],"properties":{"groupId":{"type":"string","description":"The name or id of the group to remove.","examples":["My Group"]}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"response":{"200":{"type":"object","properties":{"isSuccess":{"type":"boolean","default":true,"examples":[true]}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Groupremoveemployee = {"body":{"type":"object","required":["groupId","emails"],"properties":{"groupId":{"type":"string","description":"The group name or id.","examples":["Officevibe"]},"emails":{"type":"array","description":"The employees emails.","items":{"type":"string"}},"fromMembers":{"type":"boolean","description":"Remove the users from the Members List.","default":true},"fromManagers":{"type":"boolean","description":"Remove the users from the Managers List.","default":false}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"response":{"200":{"type":"object","properties":{"isSuccess":{"type":"boolean","default":true,"examples":[true]}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Groupsave = {"body":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"The group name. The group will be created.","examples":["My Group"]}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"response":{"200":{"type":"object","properties":{"isSuccess":{"type":"boolean","default":true,"examples":[true]}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Groupsid = {"metadata":{"allOf":[{"type":"object","properties":{"groupId":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#","description":"The name or id of the group to retrieve."}},"required":["groupId"]}]},"response":{"200":{"type":"object","properties":{"isSuccess":{"type":"boolean","default":true,"examples":[true]},"data":{"type":"object","properties":{"id":{"type":"string","examples":["9345c237-c166-48ec-af1c-705b9a057be4"]},"name":{"type":"string","examples":["Officevibe"]},"groupType":{"type":"string","examples":["Department"]},"userCount":{"type":"integer","default":0,"examples":[0]},"managerCount":{"type":"integer","default":0,"examples":[1]},"users":{"type":"array","items":{"type":"object","properties":{"email":{"type":"string","examples":["bobboby@test.com"]},"firstName":{"type":"string","examples":["Bob"]},"lastName":{"type":"string","examples":["Boby"]},"userName":{"type":"string","examples":["bobboby"]},"jobTitle":{"type":"string","examples":["Sales"]},"isGroupManager":{"type":"boolean","default":true,"examples":[true]},"isCompanyManager":{"type":"boolean","default":true,"examples":[false]},"isAdmin":{"type":"boolean","default":true,"examples":[false]}}}}}}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Groupsnameremoveallusers = {"body":{"type":"object","required":["groupId"],"properties":{"groupId":{"type":"string","description":"The group name or id."},"fromMembers":{"type":"boolean","description":"Remove the users from the Members List.","default":true},"fromManagers":{"type":"boolean","description":"Remove the users from the Managers List.","default":false}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"response":{"200":{"type":"object","properties":{"isSuccess":{"type":"boolean","default":true,"examples":[true]}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Ping = {"response":{"200":{"type":"object","properties":{"isSuccess":{"type":"boolean","default":true,"examples":[true]}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"401":{"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Poll = {"metadata":{"allOf":[{"type":"object","properties":{"status":{"type":"string","default":"Active","$schema":"https://json-schema.org/draft/2020-12/schema#","description":"The satus of the Polls to retrieve (Active, Inactive, Archived)"}},"required":[]}]},"response":{"200":{"type":"object","properties":{"pollCount":{"type":"integer","default":0,"examples":[1]},"polls":{"type":"array","items":{"type":"object","properties":{"id":{"type":"string","examples":["CQ-10446"]},"titles":{"type":"array","items":{"type":"string","examples":["How are you today?"]}},"groupNames":{"type":"array","items":{"type":"string","examples":["All Company"]}},"publishDate":{"type":"string","examples":["2016-05-30T15:00:00Z"]},"answerChoices":{"type":"array","items":{}},"answerCount":{"type":"integer","default":0,"examples":[20]}}}}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Polls = {"body":{"type":"object","required":["poll"],"properties":{"poll":{"type":"object","description":"The poll to create.","properties":{}}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"response":{"200":{"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Pollsid = {"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#","description":"The id of the Poll to retrieve."}},"required":["id"]}]},"response":{"200":{"type":"object","properties":{"id":{"type":"string","examples":["CQ-10446"]},"titles":{"type":"array","items":{"type":"string","examples":["Do you prefer cats or dogs?"]}},"groupNames":{"type":"array","items":{"type":"string","examples":["All Company"]}},"answerType":{"type":"string","examples":["List"]},"publishDate":{"type":"string","examples":["2016-05-30T15:00:00Z"]},"answerChoices":{"type":"array","items":{"type":"object","properties":{"id":{"type":"string","examples":["CQAC-0"]},"title":{"type":"string","examples":["Cats"]}}}},"answers":{"type":"array","items":{"type":"object","properties":{"creationDate":{"type":"string","examples":["2016-05-30T15:16:38.601Z"]},"content":{"type":"string","examples":["CQAC-1"]}}}},"answerCount":{"type":"integer","default":0,"examples":[1]}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Sync = {"body":{"type":"object","required":["users","groups","mappings"],"properties":{"settings":{"type":"object","description":"The synchronization settings.","required":["syncManagerEmail","inviteNewUsers"],"properties":{"syncManagerEmail":{"type":"string","description":"The sync manager's email address","default":"manager@foo.bar"},"inviteNewUsers":{"type":"boolean","description":"Whether to invite new users on creation or not","default":false}}},"users":{"type":"array","description":"The list of users to synchronize, cannot be empty","items":{"properties":{"id":{"type":"string","description":"The member's ID","default":"U001"},"email":{"type":"string","description":"The member's email address","default":"user1@foo.bar"},"firstName":{"type":"string","description":"The member's first name","default":"Foo"},"lastName":{"type":"string","description":"The member's last name","default":"Bar"},"jobTitle":{"type":"string","description":"The member's job title","default":"Job1"},"imageUrl":{"type":"string","description":"The member's profile picture","default":"http://..."},"language":{"type":"string","description":"For language, options are: English, Français, Español, Deutsch, Português","default":"English"},"Gender":{"type":"string","description":"Optionally add custom attributes by adding the key value pairs to this object.","default":"Female"}},"required":["id","email","firstName","lastName","language"],"type":"object"}},"groups":{"type":"array","description":"The list of groups to synchronize, cannot be empty","items":{"properties":{"id":{"type":"string","description":"The group's ID","default":"G001"},"name":{"type":"string","description":"The group's name","default":"Group1"}},"required":["id"],"type":"object"}},"mappings":{"type":"array","description":"The list of group hierarchy and their users' memberships, cannot be empty","items":{"properties":{"groupId":{"type":"string","description":"The ID of the group being mapped","default":"G0001"},"userId":{"type":"string","description":"The ID of the user being mapped","default":"U0001"},"subGroupId":{"type":"string","description":"The ID of the group being set as a sub group","default":"G0002"},"isMember":{"type":"boolean","description":"If the user is a member of the group or not","default":true},"isManager":{"type":"boolean","description":"If the user is the manager of the group or not","default":false}},"required":["groupId","userId","subGroupId","isMember","isManager"],"type":"object"}}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"response":{"200":{"type":"object","properties":{"isSuccess":{"type":"boolean","default":true,"examples":[true]},"errors":{"type":"array","items":{}}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Users = {"response":{"200":{"type":"object","properties":{"userCount":{"type":"integer","default":0,"examples":[1]},"users":{"type":"array","items":{"type":"object","properties":{"email":{"type":"string","examples":["bobboby@test.com"]},"firstName":{"type":"string","examples":["Bob"]},"lastName":{"type":"string","examples":["Boby"]},"userName":{"type":"string","examples":["bobboby"]},"jobTitle":{"type":"string","examples":["Sales"]},"isGroupManager":{"type":"boolean","default":true,"examples":[false]},"isCompanyManager":{"type":"boolean","default":true,"examples":[false]},"isAdmin":{"type":"boolean","default":true,"examples":[false]}}}}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Usersid = {"metadata":{"allOf":[{"type":"object","properties":{"email":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#","description":"The email of the user to retrieve"}},"required":["email"]}]},"response":{"200":{"type":"object","properties":{"email":{"type":"string","examples":["bobboby@test.com"]},"firstName":{"type":"string","examples":["Bob"]},"lastName":{"type":"string","examples":["Boby"]},"userName":{"type":"string","examples":["bobboby"]},"jobTitle":{"type":"string","examples":["Sales"]},"isGroupManager":{"type":"boolean","default":true,"examples":[false]},"isCompanyManager":{"type":"boolean","default":true,"examples":[false]},"isAdmin":{"type":"boolean","default":true,"examples":[false]},"managedGroups":{"type":"array","items":{}},"memberGroups":{"type":"array","items":{"type":"string","examples":["Officevibe"]}}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
export { Employeeremove, Employeesave, Engagement, Feedback, Feedbackid, Feedbacklabels, Feedbacklist, Group, Groupaddemployee, Groupremove, Groupremoveemployee, Groupsave, Groupsid, Groupsnameremoveallusers, Ping, Poll, Polls, Pollsid, Sync, Users, Usersid }
